### ISSUE TITLE
When the notification is clicked, it opens an non-existent folder.

### ISSUE THREAD

**Issue by aleksandar-stefanovic** [davidmhewitt/torrential#12]
It opens a folder which does not exist, sorry, I didn't record the exact name of the folder, but it contained the name of the torrent, but it wasn't the actual folder in which the torrent was downloaded. The torrent is a folder itself (not just a single file).

**Comment by davidmhewitt** [comment]
Thanks for the bug report.

Do the names of any of the folders in the path contain spaces or special characters?

There's an issue in pantheon files related to that being tracked here: https://github.com/elementary/files/issues/42

If there were no spaces or special characters, let me know and I'll investigate further.

**Comment by aleksandar-stefanovic** [comment]
I will try to recreate the bug, so I could provide more info...

**Comment by davidmhewitt** [comment]
You can right click torrents and there is an option to open them in the file browser. You should be able to recreate a bug that way as it is the same code.

**Comment by aleksandar-stefanovic** [comment]
Yes, the bug is the same as the one you pointed, it replaces spaces with zeroes.

**Comment by davidmhewitt** [comment]
There are a couple of fixes being tested for that bug in files so hopefully it will be fixed soon. I'll close this bug report since there's nothing we can do here.

Thank you for the report. Please feel free to report any other issues or suggestions.
