### ISSUE TITLE
Continuous Integration broken

### ISSUE THREAD

**Issue by peteruithoven** [davidmhewitt/torrential#123]
Looks like the Continuous Integration is broken:
```
# Internal error while running
Cannot copy 'libcrypto.0.9.8.dylib' to a subdirectory of itself, 'libcrypto.0.9.8.dylib'.
Error: Cannot copy 'libcrypto.0.9.8.dylib' to a subdirectory of itself, 'libcrypto.0.9.8.dylib'.
    at fs.readlink (/home/travis/build/davidmhewitt/torrential/node_modules/fs-extra/lib/copy/copy.js:190:21)
    at FSReqWrap.oncomplete (fs.js:141:20)
```

Doesn't seem to be change specific, it's shown in almost all PR's.

The [Travis.yml](https://github.com/davidmhewitt/torrential/blob/master/.travis.yml) contents is quite similar to the [Standard .travis.yml](https://github.com/elementary/houston/wiki/Continuous-Integration#standard-travisyml). 

**Update:** 
I tried making it the same in #124 but that didn't help.
I tried re-cloning and building the repo locally and noticed no issues.

**Comment by davidmhewitt** [comment]
I've resolved this now. There were some weird symlinks in the transmission submodule that houston didn't seem to like too much for some reason. But they weren't needed files for building torrential, so I've removed them.
