### ISSUE TITLE
Releases: missing transmission sub-module

### ISSUE THREAD

**Issue by Kjuvi** [davidmhewitt/torrential#125]
The releases contain a transmission folder which is empty. What is their purpose if we have to add the sub-module by hand before trying to compile it ?

**Comment by davidmhewitt** [comment]
The release tarballs are automatically generated, by either github or Houston (the elementary package building system) and I create release tags to indicate which commits Houston should use. So while the tarballs exist, I've never tested or used them for any purpose.

I also don't have a lot of time to work on this project, so I'd like to avoid any extra effort in generating new releases where possible.
