### ISSUE TITLE
Show status text when a torrent is being verified

### ISSUE THREAD

**Issue by Jessifir** [davidmhewitt/torrential#126]
When adding a torrent that already exists in the download location, Torrential currently just shows the torrent title and a blue progress bar slowly filling up, without any indication of what is happening.

Simply adding "verifying" status text to the torrent would remove the ambiguity. It would also probably be a good idea to style the progress bar differently (perhaps making it yellow) to provide a visual indication that a torrent is being verified.

Additionally, torrents are queued to be verified should probably say something like "waiting to verify"

**Comment by davidmhewitt** [comment]
As you know, this has now been incorporated into the code and will be available from the next release.
