### ISSUE TITLE
No option to selectively download files

### ISSUE THREAD

**Issue by aleksandar-stefanovic** [davidmhewitt/torrential#13]
There is no option to select/deselect individual files of the torrent.

**Comment by iXecFTW** [comment]
This is one of the reasons i am still using transmission. Sometimes i only want to download a few files of the torrent.

**Comment by poetfreak** [comment]
I agree completely. Required.

**Comment by WilsenHernandez** [comment]
Extra to this, there is no option to select download folder individually, must be an option too at the same time there is an option to select files.

With all files selected by default, and the default download location (previously selected in 'Preferences')
