### ISSUE TITLE
Use popover menu for the application menu

### ISSUE THREAD

**Issue by adithyankv** [davidmhewitt/torrential#161]
The general design choice within elementary OS seems to be to use popover menus for application menus, Torrential however uses the traditional `Gtk.Menu`. Perhaps change this to use the `Gtk.Popover` for design consistency? 

**screenshots**
usage in code and camera apps for reference
![popover_issue_demo](https://user-images.githubusercontent.com/29067795/149266342-83e597df-9f35-4cf2-9c10-80b4a945c159.png)

**Comment by davidmhewitt** [comment]
Fixed in #171
