### ISSUE TITLE
Making Ctrl+C optional?

### ISSUE THREAD

**Issue by spekulatius** [davidmhewitt/torrential#163]
Hey @davidmhewitt 

I've noticed that a keyboard shortcut on Ctrl+C was set with install and I couldn't find an option to remove/disable it in the settings. Maybe something to consider for improvement.

Cheers,
Peter

**Comment by spekulatius** [comment]
Also, after de-installing the program coming up and shortcut remains:

![image](https://user-images.githubusercontent.com/8433587/190991169-0a12110e-ec9a-40df-8d0c-7af503d7ff5f.png)

CC @danrabbit

**Comment by davidmhewitt** [comment]
That screenshot isn't Torrential.

**Comment by spekulatius** [comment]
I'm a bit unsure on the workings in details here. Sorry, if it might came across undesirable. I've installed torrential using the elementary appcenter and since this I've got this window each time I'm copying an URL. It's a bit tricky to work with this :rofl: Maybe it's something indirectly added? I'm not sure and will see if I can figure it...

**Comment by davidmhewitt** [comment]
The screenshot isn't Torrential, it's another application. Have you installed another torrent client?

**Comment by spekulatius** [comment]
I tried another one but uninstalled it pretty quick again after it didn't even open up.

**Comment by spekulatius** [comment]
Okay, I re-installed it and then uninstalled it again and that seems to have fixed it. Strange thing. Thank you for your help @davidmhewitt !
