### ISSUE TITLE
segfault with OpenSSL 3

### ISSUE THREAD

**Issue by tobip** [davidmhewitt/torrential#164]
I get a segfault running torrential in combination with OpenSSL 3 (openssl 3.0.7 in my case). 

Output:
```
[2022-11-23 18:56:48.883] tr_crypto_utils: OpenSSL error: error:0308010C:digital envelope routines::unsupported
[1]    143752 segmentation fault (core dumped)  torrential```

**Comment by davidmhewitt** [comment]
This is an incompatibility with Transmission 3.0 and OpenSSL 3.0. It uses some methods in OpenSSL that are now considered legacy.

I patch around it in my Flatpak with https://github.com/davidmhewitt/torrential/commit/9eb27a37134f02b52c8b16f68519544e9eacb85a but this possibly isn't suitable for other packaging methods.

Might have to wait and see what the status of Transmission 4.0 is with regards to this.
