### ISSUE TITLE
Add new translations

### ISSUE THREAD

**Issue by balzabalza** [davidmhewitt/torrential#32]
Hi,

Torrential is sleek, and I love it. The only way I can contribute is to translate all texts into Italian, and I'm willing to know if translations will be supported.

**Comment by davidmhewitt** [comment]
Hi @balzabalza ,

Someone has already submitted an Italian translation which you can see here:
https://github.com/davidmhewitt/torrential/blob/master/po/it.po

These translations will be available in the next update of Torrential. If you notice any mistakes in the translation or wish to translate new features when they become available, you can always suggest edits to the file and submit a pull request.
