### ISSUE TITLE
Brazilian portuguese translation

### ISSUE THREAD

**Issue by drakofrost** [davidmhewitt/torrential#34]
I noticed that Torrential is missing the translation for brazilian portuguese, I could translate it, if the devs are interested. As long as there is no coding involved (since I'm not a programmer), just send me a text file and I'll translate it.

**Comment by davidmhewitt** [comment]
Hi @drakofrost,

Thank you for offering to help with the translations. You can help with the translations for your language here:
https://github.com/davidmhewitt/torrential/blob/master/po/pt_BR.po

If you edit the file there and submit the changes as a branch/pull request, I will check they work and get them added in the next update.
