### ISSUE TITLE
Cannot start app after update.

### ISSUE THREAD

**Issue by harisvsulaiman** [davidmhewitt/torrential#35]
version: 1.0.5

console log 
```
com.github.davidmhewitt.torrential: symbol lookup error: com.github.davidmhewitt.torrential: undefined symbol: granite_app
```

**Comment by davidmhewitt** [comment]
Hi @harisvsulaiman ,

This would suggest that you have the latest version of Granite installed either from the elementary daily PPA or directly from the Granite github.

There are some breaking changes in the latest version of Granite that are not compatible with Torrential. I will look to see if there's anything I can do to help with this issue, but it is not a problem with Torrential itself. Just an incompatibility with the version of Granite you have installed which would not be installed in a standard elementary setup.
