### ISSUE TITLE
Magnet link support

### ISSUE THREAD

**Issue by artemanufrij** [davidmhewitt/torrential#36]
It would be very helpful to have an option to start a download from a magnet link

**Comment by davidmhewitt** [comment]
Magnet links are already supported. Torrential should launch when a magnet link is clicked.

Do you mean it would be good to have a box to paste magnet links into?

**Comment by megatux** [comment]
Right! like the "Open url..." option on Transmission app (it also takes the content of the clipboard so you don't have to paste it)

**Comment by WilsenHernandez** [comment]
Really hope to see this added soon!

**Comment by poetfreak** [comment]
ditto! :D and RSS as well would be amazing. Example: https://torrentproject.se/rss/game%20of%20thrones%20s07/ 
would download all results of game of thrones season seven... adding new episodes as they come up. ;)

**Comment by andbuitra** [comment]
Hi. Torrential is not opening when I click on the magnet link on TPB using Firefox on eOS. Any ideas on how to fix this?
