### ISSUE TITLE
Resorting continually

### ISSUE THREAD

**Issue by peteruithoven** [davidmhewitt/torrential#42]
The list seems to resort continually. It switches between these 2 states every second:
![screenshot from 2017-07-23 01 09 12](https://user-images.githubusercontent.com/523210/28495209-ba65c684-6f46-11e7-92ce-2a3e58523e4a.png)
![screenshot from 2017-07-23 01 09 37](https://user-images.githubusercontent.com/523210/28495208-b9c91244-6f46-11e7-83ca-d25377c4b9ab.png)
How does Torrential sort the items? 

I'm running 1.0.5 on Elementary OS 0.4.1 Loki.

Please let me know if can to provide more information or I can test something.

**Comment by davidmhewitt** [comment]
It should sort torrents that are downloading to the top of the list and then by the date in which they were added.

The torrent that is moving up and down the list, it looks as though it is paused but also complete?

**Comment by peteruithoven** [comment]
Alright, and how are items that have the same state (downloading / seeding / paused) sorted? 

I'm also seeing the issue within items that are all seeding for example. 

> The torrent that is moving up and down the list, it looks as though it is paused but also complete?
Yeah, that's also somewhat weird, when I press play again, it's switching back to paused.

**Comment by peteruithoven** [comment]
I've tried this again with some legit sources, like:
- [Ubuntu](http://releases.ubuntu.com/16.04/ubuntu-16.04.2-desktop-amd64.iso.torrent)
- [ElementaryOS](magnet:?xt=urn:btih:1f40a018f69eaabf9b05429f6d52160af4affb91&dn=elementaryos-0.4.1-stable.20170517.iso&tr=https%3A%2F%2Fashrise.com%3A443%2Fphoenix%2Fannounce&tr=udp%3A%2F%2Fopen.demonii.com%3A1337%2Fannounce&tr=udp%3A%2F%2Ftracker.ccc.de%3A80%2Fannounce&tr=udp%3A%2F%2Ftracker.openbittorrent.com%3A80%2Fannounce&tr=udp%3A%2F%2Ftracker.publicbt.com%3A80%2Fannounce&ws=http://ams3.dl.elementary.io/download/MTUwMDc3MDQ2Mg==/elementaryos-0.4.1-stable.20170517.iso)

And [some torrents that come preloaded with Webtorrent](https://github.com/webtorrent/webtorrent.io/tree/master/static/torrents), but can't reproduce the issue.

I usually use magnet links, do you know of a good source of test magnets links?

**Comment by peteruithoven** [comment]
Looking into this, the list component''s [sort function](https://github.com/davidmhewitt/torrential/blob/master/src/Widgets/TorrentListBox.vala#L152-L161), uses the `date_added` property of the torrents that are added, but  it looks like the torrent [date_added getter](https://github.com/davidmhewitt/torrential/blob/master/src/Torrent.vala#L194-L202) can fall back to `time_t ()`. 
Couldn't that result in the same `date_added` for multiple torrents? 

And / or maybe, because `date_added` works in seconds, it's not precise enough to distinguish from rapidly added torrents? (when using magnets links it's quite easy to open 2 in a second)

**Comment by peteruithoven** [comment]
Thanks!

**Comment by peteruithoven** [comment]
Nice! With the 1.0.6 release I can't reproduce the issue anymore.
