### ISSUE TITLE
It's not possible to quit torrential from desktop

### ISSUE THREAD

**Issue by artemanufrij** [davidmhewitt/torrential#45]
if `Continue Download when closed` is activated, it's not possible to quit it. It would be useful to have a menu item in Desktop file:
![close torrential](https://user-images.githubusercontent.com/16517095/28994600-7f0da732-79d2-11e7-8cc0-b137c7a2e97d.png)

**Comment by jtrees** [comment]
I agree that this is missing. There is a workaround though: Ctrl+Q
