### ISSUE TITLE
Not possible to disable upload

### ISSUE THREAD

**Issue by TicTac7x** [davidmhewitt/torrential#51]
Make it possible to disable uploading.

**Comment by poetfreak** [comment]
this can't really be done... as it just gets your client banned. Then, other torrent clients will not share or communicate with you. Sharaza did this back in the day. :D 
Pretty soon, not of the other torrent clients would talk to sharaza.
you can set your ratio to .01 so it stops uploads the moment you are done already.

**Comment by TicTac7x** [comment]
It's possible with transmission. You can set the upload speed to 0 and seeding ratio to 0. Is this possible with this app?

**Comment by davidmhewitt** [comment]
As stated above, it's against the spirit of torrenting to not upload at least some share back. If everyone disabled uploads, torrents wouldn't work at all.

It's possible to set your seed ratio/speeds quite low in Torrential and I consider that to be sufficient for most needs, so I'm going to close this as won't fix.
