### ISSUE TITLE
Can't sudo make uninstall

### ISSUE THREAD

**Issue by cassidyjames** [davidmhewitt/torrential#57]
If I build and install locally, I can't `sudo make uninstall` to remove it. :stuck_out_tongue:

**Comment by davidmhewitt** [comment]
This is common with CMake projects as CMake does not provide an uninstall target.

However, CMake does generate a list of the files it installed in `install_manifest.txt`. So with some linux command magic, you can use the following to do the equivalent.

`cat install_manifest.txt | sudo xargs rm`
