### ISSUE TITLE
Sync Libtransmission with upstream

### ISSUE THREAD

**Issue by KingLucius** [davidmhewitt/torrential#62]
You need to sync libtransmission with the upstream so this project doesn't get outdated.
Changes mostly bugfixes, I don't think you'll need to play with .vapi with every change.

**Comment by davidmhewitt** [comment]
I agree that this is quite important, so thank you for adding it to my list.

The plan is to try and include libtransmission as a git submodule which will hopefully make it easier to maintain and pull changes from upstream.

However, the current blocker to that is that Houston (the elementary AppCenter backend) does not support git submodules. I'm going to look at submitting a PR to Houston to add this when I get chance.

**Comment by davidmhewitt** [comment]
Fixed in 28628ecaa721270ad4ed5f0a636dac45c2d10495
