### ISSUE TITLE
"Open Magnet Link" Icon

### ISSUE THREAD

**Issue by mattperr827** [davidmhewitt/torrential#63]
First of all, I just started using Torrential and it's amazing. I was wondering if in the next update, the icon for "Open Magnet Link" could be updated slightly. I feel like the icon is out of place and could be improved if it looked more like the "Open .torrent file" icon. Besides that, everything works flawlessly so far.

**Comment by davidmhewitt** [comment]
It already looks pretty similar to the other icon:

![image](https://user-images.githubusercontent.com/3372394/31362386-2136a08a-ad50-11e7-862e-20f7143fe1be.png)

Can you explain more how you think this could be improved?

**Comment by mattperr827** [comment]
![screenshot from 2017-10-09 18 20 12](https://user-images.githubusercontent.com/32655293/31362525-90fe9670-ad1e-11e7-8586-7e6359301be5.png)
I realize now that it is because the ePapirus theme doesn't have the icon included. My apologies.

**Comment by davidmhewitt** [comment]
No problem. Torrential is only tested with the official elementary icon theme and stylesheet. I can't guarantee it will look good in every theme combination.

**Comment by mattperr827** [comment]
You wouldn't happen to know what to know the .svg in icons/ePapirus/16x16/actions so that I can add an image for the "open magnet link" icon? I believe I found the image for the "open .torrent file" icon and it was labeled document-open.svg. I tried naming an image magnet-open.svg but unfortunately that didn't work. Thanks again.

**Comment by davidmhewitt** [comment]
I don't think there is a standard icon name for the open magnet link action as it isn't a very commonly used one.

Currently, that icon is bundled inside the executable for Torrential, so there's no easy way of changing it. I'll look into how possible it would be to be able to override it more easily for future releases, but I'm afraid it's stuck with that icon for now.
