### ISSUE TITLE
Seeding seems to stop...

### ISSUE THREAD

**Issue by ghost** [davidmhewitt/torrential#68]
It seems that when I restart my computer the torrents I've downloaded seem to stop seeding. Sometimes they start seeding again and sometimes they don't. I downloaded a vanilla flavor of Transmission GTK+ and it seeds no matter what. So am I doing something wrong or is this an actual issue?

**Comment by davidmhewitt** [comment]
May be fixed after #89 is closed. As there have been no more reports of this and the original poster is gone, I'll close this for now and it can be re-opened if anyone else experiences this issue.
