### ISSUE TITLE
Use "tabbar" filter instead of sidebar

### ISSUE THREAD

**Issue by danrabbit** [davidmhewitt/torrential#7]
Since you have only a few static items, it would be more space efficient to use a ModeButton to filter instead of a sidebar.

**Comment by davidmhewitt** [comment]
@danrabbit In the header bar like AppCenter?

**Comment by danrabbit** [comment]
Could be, but if there's not room could also just be right above the list view like Transmission:

![](https://macfreeware.files.wordpress.com/2008/03/transmission.png)

**Comment by davidmhewitt** [comment]
Fixed in dad42e9db1dff453ba31ea992d24354ec54b165e
