### ISSUE TITLE
Hardcoded icon open-magnet

### ISSUE THREAD

**Issue by varlesh** [davidmhewitt/torrential#74]
Why `open-magnet` icon hardcoded? It's not good looking for non-elementary icon themes:
`var magnet_image = new Gtk.Image.from_resource ("/com/github/davidmhewitt/torrential/open-magnet.svg");`
![image](https://user-images.githubusercontent.com/8083855/32938647-519c61b0-cb96-11e7-90b4-8088f32f4f7d.png)

**Comment by davidmhewitt** [comment]
This has been fixed in https://github.com/davidmhewitt/torrential/commit/c8797e628afbaf73b61e6071f82d87317b17c8ce

The fix will be present in the next release. If the icon theme provides `open-magnet`, it should be used instead.
