### ISSUE TITLE
Make libunity dependency optional

### ISSUE THREAD

**Issue by Saroufim** [davidmhewitt/torrential#79]
I've been trying to create a Flatpak bundle for Torrential. However, I'm stuck at compiling Libunity. It requires libdee and libdee seems to have certain issues. Is it possible to either make Libunity optional or provide a flatpak bundle yourselves?

**Comment by davidmhewitt** [comment]
Hi,

Thank you for your report. I'm personally not interested in creating a Flatpak bundle myself as elementary AppCenter provides a small income stream for this application that Flatpak would not. I'll consider making libunity an optional dependency as it won't be around forever, with unity not being supported by canonical anymore, etc...

But, that'll be fairly low on my priority list as it works fine as it is for now on elementary, which is the platform I concentrate on supporting.

I'd happily accept a PR to make the libunity support optional, however. I've renamed your issue accordingly.

Thank you,
David

**Comment by danirabbit** [comment]
Looks like this was fixed in #155
