### ISSUE TITLE
Taking too much time to begin download

### ISSUE THREAD

**Issue by infuerano** [davidmhewitt/torrential#83]
Hi,
Thanks for this awesome app. I have downloaded it free so i don't know if i am qualified to report problem. I kinda feel bad :( .  I would like to tell that if i add torrent link in this app compared to deluge it starts the downloading process way too later. I meant deluge start file downloading within 30 second but torrential take more than 4 to 5 mins.

**Comment by davidmhewitt** [comment]
Hi,

Thank you for the bug report and apologies for the slow reply. If you still can, would it be possible for you to run Torrential from the terminal with `com.github.davidmhewitt.torrential` and then try and reproduce the behaviour above.

If you leave it running for a few minutes before copying the output, it should contain information about why it is taking so long to start downloading the torrent.

**Comment by davidmhewitt** [comment]
This may have been resolved in the most recent version (1.0.9) which is now available on AppCenter. If you are still experiencing issues, please leave another comment with the information I have requested above and I'll re-open the issue.
